---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: mockbin-tls
    service.beta.openshift.io/serving-cert-secret-name: mockbin-tls
  labels:
    app: mockbin
    app.kubernetes.io/component: api
    app.kubernetes.io/name: mockbin
  name: mockbin
  namespace: team-b
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: mockbin
  type: ClusterIP
